markdown: rdiscount
pygments: true
permalink: /posts/:title
auto: true
rdiscount:
  extensions: [smart]

name: Omar Miah
url: http://Omarmiah.com
description: A fantastic blog that is fantastic.
twitter:
github: Omiah
gravatar_url: http:
